vicuna-7b-v1.5-test:
  prompt_template: "vicuna-7b-v1.5-test/prompt.txt"
  fn_completions: "huggingface_custom_completions"
  completions_kwargs:
    model_name: "lmsys/vicuna-7b-v1.5"
    AB_dict: null
    loqer_config: null
    model_kwargs:
      torch_dtype: "bfloat16"
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Vicuna 7B v1.5 (Test Extended API)"
  link: "https://huggingface.co/lmsys/vicuna-7b-v1.5"
